# Generated by Django 4.2.6 on 2025-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="sms_quota",
            field=models.IntegerField(default=5),
        ),
    ]
