# Generated by Django 4.2.6 on 2025-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_sms_quota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="sms_quota",
            field=models.IntegerField(default=10),
        ),
    ]
