# Generated by Django 4.2.6 on 2025-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forwarder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.CharField(default=8801760001377, max_length=15),
            preserve_default=False,
        ),
    ]
