# Generated by Django 4.2.6 on 2025-03-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_customer_sms_quota"),
        ("forwarder", "0002_message_inappropiate_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="customer.customer",
            ),
        ),
    ]
