# Generated by Django 4.2.6 on 2025-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forwarder", "0003_message_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="inappropiate_content",
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("SENT", "Sent"),
                    ("RECEIVED", "Received"),
                    ("FAILED", "Failed"),
                    ("REJECTED", "Rejected"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
