# Generated by Django 4.2.6 on 2025-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
