# Generated by Django 4.2.6 on 2025-03-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("total_sms_quota", models.IntegerField(default=0)),
            ],
        ),
    ]
